# Generated by Django 6.0.5 on 2026-06-21 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('Amazing', 'Amazing'), ('Happy', 'Happy'), ('Relaxed', 'Relaxed'), ('Okay', 'Okay'), ('Tired', 'Tired'), ('Sad', 'Sad'), ('Anxious', 'Anxious'), ('Angry', 'Angry')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoodLogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mood_tracker_app.moodlog')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mood_tracker_app.tag')),
            ],
        ),
    ]
