# Generated by Django 6.0.5 on 2026-06-21 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_user_is_active'),
        ('mood_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodlog',
            name='mood_score',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='moodlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.user'),
        ),
    ]
